FROM python:3.13-bookworm

WORKDIR /app

COPY requirements/requirements.txt requirements/requirements.txt

RUN pip install --no-cache-dir -r requirements/requirements.txt

COPY . .

EXPOSE 8080

CMD ["uvicorn", "spaceship.main:app", "--host", "0.0.0.0", "--port", "8080"]
